### ISSUE TITLE
Grafana: SMTP Notification settings in grafana.ini

### ISSUE THREAD

**Issue by devax** [eth2-educators/eth-docker#283]
Hi all,
I'd like to setup email notification (SMTP notification) for alerting. To do so, I need to modify `grafana.ini` and add my smtp settings. As I understand, the file is located at `/etc/grafana/grafana.ini`, but this seems not to be in a persisted volume, so changes to that file will not survive container recreations. Is there a way to modify `grafana.ini` in a way that settings will be persisted?
I cannot find anything about that subject in the docs but I can hardly imagine that I'm the only one trying to set this up. Am I missing something obvious here?

**Comment by yorickdowne** [comment]
Interesting. So far all alerting has been via the built-in methods for Grafana that don't require changes to the .ini. I'll take a look and see what can be done.

**Comment by devax** [comment]
Thanks for your feedback. Seems like e-mail notification is not a commonly requested feature. Are there any insights in what service people actually use for notifications?

**Comment by fmoledina** [comment]
@devax , you could do this by creating a `grafana-smtp.yml` file with the following content:

```yaml
version: "3.4"
services:
  grafana:
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mail.example.com:<port>
      - GF_SMTP_USER=admin@example.com
      - GF_SMTP_PASSWORD=password
      - GF_SMTP_FROM_ADDRESS=admin@example.com
      - GF_SMTP_FROM_NAME="Rocketpool Grafana Admin"
```

Then add the `grafana-smtp.yml` to your `COMPOSE_FILE` environment variable in `.env`. This method can be used to add any [Grafana configuration items](https://grafana.com/docs/grafana/latest/administration/configuration/) via environment variables.
